# WHY Nginx
# 1. For load balancing - see below
# 2. For reverse proxy - early termination of SSL invalid connection
# 3. For rate limiting
# 4. For security - since our servers are not exposed directly to the client

# this conf file and the logs should be at default nginx location
worker_processes  auto; # number of worker processes nginx will use, auto will be replaced with no of cpu cores
events {
    worker_connections  1024; # no of connections 1 worker process can handle
}
http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s; # rate limitng in Nginx based on IP
    limit_req_status 429;  # Too Many Requests
    # list all individual node servers which needs to be load balanced
    upstream my_cluster_nodes {
        # least_conn # load balancing algo
        #  hash $remote_addr consistent; - for using consistent hasing algo, not available in ALB (see below on ALB vs Nginx)
        # rebalancing will be done by NginX only, once we add / remove upstream server, then restart NginX  command(nginx -s reload)
        server 127.0.0.1:3001; # these servers we created in dockercompose file
        server 127.0.0.1:3002;
        server 127.0.0.1:3003;
    }
    server {
        listen       8080; # port on which nginx server will run
        server_name  localhost; # hostname for nginx server

        location / { # / means hostname/ all sub request will have below confix
            proxy_pass http://my_cluster_nodes; # nginx to proxy client request to upstream - my_cluster_nodes which we created above
            # notice we need to add http protocol in above proxy_pass
        }
    }
}

# NGINX on AWS - 
# In AWS we can use ALB (Application load balancer), but it has limited algo, like only roundrobin / least_conn
# But I need to use consistent hash algo, then need to go with nginx
# SO on AWS keep a separte instance of EC2 (micro) which will just have nginx and which will add upstream IPs for all other EC2s
# docker image for ec2 would be 
# From nginx:stable

# Basic Nginx commands
# Start Nginx - sudo systemctl start nginx
# Stop Nginx - sudo systemctl stop nginx
# Restart Nginx - sudo systemctl restart nginx
# Reload config without downtime - sudo systemctl reload nginx
# Check status - sudo systemctl status nginx

# systemctl is a command-line tool used to manage systemd services on Linux
